server:
  port: 8081
  servlet :
    context-path: /restaurant
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    health:
      show-details: always
spring:
  jackson:
     default-property-inclusion: non_null
